services:
  kernel.event_listener.json_request_transformer:
    class: Opstalent\ApiBundle\EventListener\JsonRequestTransformerListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

  kernel.event_subscriber.response_serializer:
    class: Opstalent\ApiBundle\EventListener\ResponseSerializerSubscriber
    arguments:
      - "@router"
      - "@opstalent.api_bundle.serializer_service"
    tags:
      - { name: kernel.event_subscriber }

  kernel.event_subscriber.cors:
    class: Opstalent\ApiBundle\EventListener\CORSSubscriber
    arguments:
        - "@router"
    tags:
        - { name: kernel.event_subscriber }

  kernel.event_subscriber.controller_lifecycle:
    class: Opstalent\ApiBundle\EventListener\ControllerLifecycleSubscriber
    arguments:
        - '@event_dispatcher'
    tags:
        - { name: kernel.event_subscriber }

  kernel.event_subscriber.response_wrapper:
    class: Opstalent\ApiBundle\EventListener\ResponseWrapperSubscriber
    arguments:
        - '@logger'
    tags:
      - { name: kernel.event_subscriber }

  kernel.event_subscriber.repository_caller:
    class: Opstalent\ApiBundle\EventListener\RepositoryCallerSubscriber
    arguments:
      - "@router"
      - "@service_container"
    tags:
      - { name: kernel.event_subscriber }

  kernel.event_subscriber.param_resolver:
    class: Opstalent\ApiBundle\EventListener\ParamResolverSubscriber
    arguments:
      - "@router"
      - "@service_container"
    tags:
      - { name: kernel.event_subscriber }

  kernel.event_subscriber.api.annotation_resolver:
    class: Opstalent\ApiBundle\EventListener\AnnotationResolverSubscriber
    arguments:
      - "@annotation_reader"
    tags:
      - { name: kernel.event_subscriber }

  opstalent.api_repository.event_subscriber.repository_query:
    class: Opstalent\ApiBundle\EventListener\RepositoryEventSubscriber
    arguments:
      - "@opstalent.api_bundle.resolver.column_type"
    tags:
      - { name: kernel.event_subscriber }

  opstalent.api_bundle.resolver.column_type:
    class: Opstalent\ApiBundle\Resolver\ColumnTypeResolver
    arguments:
      - "@doctrine.orm.entity_manager"

  opstalent.api_bundle.normalizer.datetime:
    class: Opstalent\ApiBundle\Service\DateTimeNormalizerService
  opstalent.api_bundle.normalizer.array_collection:
    class: Opstalent\ApiBundle\Service\ArrayCollectionNormalizerService
  opstalent.api_bundle.normalizer.object:
    class: Opstalent\ApiBundle\Service\ObjectNormalizerService
    parent: serializer.normalizer.object
  opstalent.api_bundle.serializer_service:
    class: Opstalent\ApiBundle\Service\SerializerService
    arguments:
      - ["@opstalent.api_bundle.normalizer.array_collection", "@opstalent.api_bundle.normalizer.datetime", "@opstalent.api_bundle.normalizer.object"]
      - ["@serializer.encoder.json"]
      - "@security.token_storage"
